package gr.hua.dit.compilers;

import java_cup.runtime.*;

parser code {:
    // Connect this parser to a scanner!
    Lexer lexer;
    public parser(Lexer lexer) {
        super(lexer);
        this.lexer = lexer;
    }
:}

/* Terminals (tokens returned by the scanner). */
/* Keywords */
terminal AND, BOOL, CHAR, DECL, DEF,
          ELSE, ELSIF, END, EXIT, FALSE,
          FOR, HEAD, IF, INT, LIST,
          MOD, NEW, NIL, NILQ, NOT,
          OR, REF, RETURN, SKIP, TAIL,
          TRUE;

/* Operators */
terminal PLUS, MINUS, MULT, DIV, HASH, EQ, NEQ, LT,
          GT, LEQ, GEQ;

/* Seperators */
terminal LPAR, RPAR, LBRAC, RBRAC, COMMA, SEMICOLON, COLON, ASSIGN;

/* Constants and identifiers */
terminal String IDENTIFIER, STRING;
terminal Character CHARACTER;
terminal Integer INTEGER;

/* Non-terminals */
non terminal Object program;

/* The grammar */
program ::= /* empty */ ;
